/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Employee = IDL.Record({
  'da' : IDL.Float64,
  'id' : IDL.Text,
  'pf' : IDL.Float64,
  'ta' : IDL.Float64,
  'esi' : IDL.Float64,
  'hra' : IDL.Float64,
  'tds' : IDL.Float64,
  'otherAllowances' : IDL.Float64,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'isActive' : IDL.Bool,
  'dateOfJoining' : IDL.Text,
  'otherDeductions' : IDL.Float64,
  'department' : IDL.Text,
  'basicSalary' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const YTDTotals = IDL.Record({
  'totalDeductions' : IDL.Float64,
  'employeeName' : IDL.Text,
  'totalNetSalary' : IDL.Float64,
  'employeeId' : IDL.Text,
  'totalGrossSalary' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'totalNetSalary' : IDL.Float64,
  'departmentBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const DeductionSummary = IDL.Record({
  'totalPF' : IDL.Float64,
  'totalESI' : IDL.Float64,
  'totalTDS' : IDL.Float64,
  'totalOtherDeductions' : IDL.Float64,
});
export const SalaryRecord = IDL.Record({
  'da' : IDL.Float64,
  'id' : IDL.Text,
  'pf' : IDL.Float64,
  'ta' : IDL.Float64,
  'esi' : IDL.Float64,
  'hra' : IDL.Float64,
  'tds' : IDL.Float64,
  'month' : IDL.Nat,
  'totalDeductions' : IDL.Float64,
  'otherAllowances' : IDL.Float64,
  'year' : IDL.Nat,
  'basicPay' : IDL.Float64,
  'netSalary' : IDL.Float64,
  'processedAt' : IDL.Int,
  'employeeId' : IDL.Text,
  'grossSalary' : IDL.Float64,
  'otherDeductions' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkProcessSalaries' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'getAllYTDTotals' : IDL.Func([IDL.Nat], [IDL.Vec(YTDTotals)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [DashboardStats],
      ['query'],
    ),
  'getDeductionSummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [DeductionSummary],
      ['query'],
    ),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
  'getEmployeeSalaryHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SalaryRecord)],
      ['query'],
    ),
  'getSalaryRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [SalaryRecord],
      ['query'],
    ),
  'getSalaryRegister' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(SalaryRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYTDTotals' : IDL.Func([IDL.Text, IDL.Nat], [YTDTotals], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'processSalary' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEmployee' : IDL.Func([Employee], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Employee = IDL.Record({
    'da' : IDL.Float64,
    'id' : IDL.Text,
    'pf' : IDL.Float64,
    'ta' : IDL.Float64,
    'esi' : IDL.Float64,
    'hra' : IDL.Float64,
    'tds' : IDL.Float64,
    'otherAllowances' : IDL.Float64,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'isActive' : IDL.Bool,
    'dateOfJoining' : IDL.Text,
    'otherDeductions' : IDL.Float64,
    'department' : IDL.Text,
    'basicSalary' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const YTDTotals = IDL.Record({
    'totalDeductions' : IDL.Float64,
    'employeeName' : IDL.Text,
    'totalNetSalary' : IDL.Float64,
    'employeeId' : IDL.Text,
    'totalGrossSalary' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'totalNetSalary' : IDL.Float64,
    'departmentBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const DeductionSummary = IDL.Record({
    'totalPF' : IDL.Float64,
    'totalESI' : IDL.Float64,
    'totalTDS' : IDL.Float64,
    'totalOtherDeductions' : IDL.Float64,
  });
  const SalaryRecord = IDL.Record({
    'da' : IDL.Float64,
    'id' : IDL.Text,
    'pf' : IDL.Float64,
    'ta' : IDL.Float64,
    'esi' : IDL.Float64,
    'hra' : IDL.Float64,
    'tds' : IDL.Float64,
    'month' : IDL.Nat,
    'totalDeductions' : IDL.Float64,
    'otherAllowances' : IDL.Float64,
    'year' : IDL.Nat,
    'basicPay' : IDL.Float64,
    'netSalary' : IDL.Float64,
    'processedAt' : IDL.Int,
    'employeeId' : IDL.Text,
    'grossSalary' : IDL.Float64,
    'otherDeductions' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkProcessSalaries' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'getAllYTDTotals' : IDL.Func([IDL.Nat], [IDL.Vec(YTDTotals)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [DashboardStats],
        ['query'],
      ),
    'getDeductionSummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [DeductionSummary],
        ['query'],
      ),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
    'getEmployeeSalaryHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getSalaryRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [SalaryRecord],
        ['query'],
      ),
    'getSalaryRegister' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYTDTotals' : IDL.Func([IDL.Text, IDL.Nat], [YTDTotals], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'processSalary' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEmployee' : IDL.Func([Employee], [], []),
  });
};

export const init = ({ IDL }) => { return []; };