/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalEmployees' : bigint,
  'totalNetSalary' : number,
  'departmentBreakdown' : Array<[string, number]>,
}
export interface DeductionSummary {
  'totalPF' : number,
  'totalESI' : number,
  'totalTDS' : number,
  'totalOtherDeductions' : number,
}
export interface Employee {
  'da' : number,
  'id' : string,
  'pf' : number,
  'ta' : number,
  'esi' : number,
  'hra' : number,
  'tds' : number,
  'otherAllowances' : number,
  'name' : string,
  'designation' : string,
  'isActive' : boolean,
  'dateOfJoining' : string,
  'otherDeductions' : number,
  'department' : string,
  'basicSalary' : number,
}
export interface SalaryRecord {
  'da' : number,
  'id' : string,
  'pf' : number,
  'ta' : number,
  'esi' : number,
  'hra' : number,
  'tds' : number,
  'month' : bigint,
  'totalDeductions' : number,
  'otherAllowances' : number,
  'year' : bigint,
  'basicPay' : number,
  'netSalary' : number,
  'processedAt' : bigint,
  'employeeId' : string,
  'grossSalary' : number,
  'otherDeductions' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YTDTotals {
  'totalDeductions' : number,
  'employeeName' : string,
  'totalNetSalary' : number,
  'employeeId' : string,
  'totalGrossSalary' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkProcessSalaries' : ActorMethod<[bigint, bigint], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'getAllYTDTotals' : ActorMethod<[bigint], Array<YTDTotals>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[bigint, bigint], DashboardStats>,
  'getDeductionSummary' : ActorMethod<[bigint, bigint], DeductionSummary>,
  'getEmployee' : ActorMethod<[string], Employee>,
  'getEmployeeSalaryHistory' : ActorMethod<[string], Array<SalaryRecord>>,
  'getSalaryRecord' : ActorMethod<[string, bigint, bigint], SalaryRecord>,
  'getSalaryRegister' : ActorMethod<[bigint, bigint], Array<SalaryRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYTDTotals' : ActorMethod<[string, bigint], YTDTotals>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllEmployees' : ActorMethod<[], Array<Employee>>,
  'processSalary' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEmployee' : ActorMethod<[Employee], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];